import Navbar from "./components/Navbar";
import "./globals.css";


export const metadata = {
  title: "Route Groups",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        <main>
          <Navbar />
        {children}
        </main>
        </body>
    </html>
  );
}
