import "./globals.css"

export const metadata = {
  title: "Custom not found page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <main className="flex h-screen w-full bg-black text-white flex-col justify-between items-center">
        <header>Header</header>
        <div className="w-full">
        {children}
        </div>
        <footer>Footer</footer>
        </main>
        </body>
    </html>
  );
}
